commands = [
  # { item_spawner = "u", hotkey_back = "q", hotkey_close = "escape" },

  { savefile_manager = "o", hotkey_back = "q", hotkey_close = "escape" },
  { flag = "one_shot" },
  { flag = "no_damage", hotkey = "1" },
  { flag = "no_dead", hotkey = "2" },
  { flag = "no_update_ai", hotkey = "3" },
  { flags = ["no_goods_consume", "no_arrows_consume"], label = "Inf Consumables" },
  { flag = "no_stamina_consume" },
  { flags = ["no_fp_consume", "no_ashes_of_war_fp_consume"], label = "Inf Focus" },

  # These flags are probably not that useful.
  # { flag = "no_hit" },
  # { flag = "no_attack" },
  # { flag = "no_move" },

  { flag = "gravity", hotkey = "4" },

  { flag = "hitbox_high", hotkey = "5" },
  { flag = "hitbox_low", hotkey = "6" },
  { flag = "hitbox_character", hotkey = "7" },
  { flags = ["weapon_hitbox1", "weapon_hitbox2", "weapon_hitbox3"], hotkey = "8", label = "Weapon hitboxes" },
  { flag = "display_stable_pos" },
  { flag = "show_map" },
  { flag = "show_chr" },

  # These flags are currently broken for some reason. TODO investigate.
  # { flags = ["field_area_direction", "field_area_altimeter" , "field_area_compass"], hotkey = "9", label = "Field area HUD" },

  { position = "H", modifier = "rshift" },
  { position = "J", modifier = "rshift" },
  # Decomment the following line if you want an extra save/load position.
  # { position = "K", modifier = "rshift" },
  { runes = 10000, hotkey = "9" },

  { quitout = "P" },
]

[settings]
log_level = "DEBUG"
display = "0"
